### ISSUE TITLE
Where's the book already?

### ISSUE THREAD

**Issue by jeffgerickson** [jeffgerickson/algorithms#1]
The book was supposed ot be out over the summer.  Where is it?  These constant delays are completely unprofessional!

**Comment by jeffgerickson** [comment]
"Final" pre-publication draft uploaded.  Expect a new revision (if only the copyright page) after KDP actually accepts the manuscript.

**Comment by plin25** [comment]
It's here, it's here! https://www.amazon.com/dp/1792644833/
