### ISSUE TITLE
The formula is incorrect

### ISSUE THREAD

**Issue by wuloop** [jeffgerickson/algorithms#101]
**Please verify that the error is present in the most recent revision before reporting.**

**Chapter number or note title:** 
00-intro 

**Page number:** [page]
Page number 4

**Error description:**  
The _K_ in the formula _z=x*y_ should be 0 to ****m+n-2**,** because max(i) is **m-1** and max(j) is **n-1**. 

**Suggested fix (if any):** [fix]
The _K_ in the formula _z=x*y_ should be 0 to ****m+n-2**.

**Comment by Zacharyzqc** [comment]
I have the same opinion

**Comment by jeffgerickson** [comment]
You forgot about carries.  Consider 999 * 999 = 998001.  Here m = n = 3, and the product has m+n = 6 digits.
