### ISSUE TITLE
described in Al-Kitab

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [jeffgerickson/algorithms#102]
page 2

> The methods described in Al-Kitab¯, using either written figures
or counting stones, became known in English as algorism or augrym, and its
figures became known in English as ciphers.

al kitab means ```the book``` in arabic. maybe a change to ```Al-Kitab al-mukhtasar``` or ```al-mukhtasar```

**Comment by jeffgerickson** [comment]
Good point, but I've already replaced "al-Kitab" with "this latter treatise".

_Al-Kitab al-mukhtasar_ describes algebra—mostly solving quadratic equations—not decimal arithmetic.  That was the different treatise that I mention (but don't name, because it's known only in Latin translation).

**Comment by Abdur-rahmaanJ** [comment]
@jeffgerickson fine then. as a side note, the notes to read those other books before was really nice! the issue can be closed?

**Comment by jeffgerickson** [comment]
I'll close it after I upload the revision here.
