### ISSUE TITLE
[Oops.] Minor typo in section 5.3

### ISSUE THREAD

**Issue by rod-lin** [jeffgerickson/algorithms#108]
**Please verify that the error is present in the most recent revision before reporting.** yes

**Chapter number or note title:** [title] section 5.3(basic graph algorithms)

**Page number:** [page] p193(probably an older version)

**Error description:** [error] The last sentence of 5.3 probably should read "a graph is a pair of sets of things"

**Suggested fix (if any):** [fix] ^

**Comment by jeffgerickson** [comment]
No, the sentence is written exactly as intended.  A graph is a **set** of **pairs** of things.  The "things" are the vertices; the pairs are the edges.
