### ISSUE TITLE
[Oops.] Minor typo in Chapter 7 page 256

### ISSUE THREAD

**Issue by yaowang2018** [jeffgerickson/algorithms#110]
**Please verify that the error is present in the most recent revision before reporting.**

Done.

**Chapter number or note title:** [title]

Chapter 7 Minimum Spanning Trees

**Page number:** [page]

256

**Error description:** [error]

At the beginning of the second line of the third paragraph of the proof of Lemma 7.1 contains a repeating "the".

**Suggested fix (if any):** [fix]

delete one of the repeating "the".

**Comment by plin25** [comment]
Duplicate of #11
