### ISSUE TITLE
[Oops.]On page 280 chapter 8 there is a minor typo. Index i instead of j on lines 6 and 7

### ISSUE THREAD

**Issue by jamartinec** [jeffgerickson/algorithms#112]
**Please verify that the error is present in the most recent revision before reporting.**

**Chapter number or note title:** [title]

**Page number:** [page]

**Error description:** [error]

**Suggested fix (if any):** [fix]

**Comment by jeffgerickson** [comment]
Specifically: "either dist(v_i) ≤ dist(v_{j−1}) + 1 already, or we set dist(v_i) ← dist(v_{j−1}) + 1."  Both instances of v_i should be v_j
