### ISSUE TITLE
Possible error in longest increasing subsequence solution (using array indices) 

### ISSUE THREAD

**Issue by Bibeknam** [jeffgerickson/algorithms#115]
**Chapter number or note title:** 02 Backtracking

**Page number:** 18

**Error description:** While checking whether the next number is less than or equal to the current number, the expressions on both sides of <= are incorrect (using indices pseudocode)

**Suggested fix (if any):** A[1] <=  *prev*  must be replaced by A[j] <= A[i]

**Comment by TruongQToan** [comment]
I have already come over that too.

**Comment by jeffgerickson** [comment]
Already fixed.
