### ISSUE TITLE
[Oops.] I doubt that problem 4 on chapter 0 is wrong

### ISSUE THREAD

**Issue by TruongQToan** [jeffgerickson/algorithms#117]
**Please verify that the error is present in the most recent revision before reporting.**

**Chapter number or note title:** [title]
Chapter 0: introduction
**Page number:** [page]
19
**Error description:** [error]
What is the condition of R and n so that the inequality on question (a) satisfy. When I try R=n or R=n+1, it seems like the inequality is not true for all i.
**Suggested fix (if any):** [fix]

**Comment by jeffgerickson** [comment]
Duplicate of #85; already fixed.
