### ISSUE TITLE
[Oops.] Typo in Figure 8.17 - chapter 8 - page 292

### ISSUE THREAD

**Issue by gsk12** [jeffgerickson/algorithms#121]
**Chapter number:** 8

**Page number:** 292

**Error description:** 
Typo in Figure 8.17, chapter 8, page 292: 0th edition (pre-publication draft) — December, 2018

![image](https://user-images.githubusercontent.com/10239894/55687051-2d023d80-592e-11e9-8809-f58b88ad8420.png)

**Suggested fix:** 
In the image caption it should probably read:  "pulled from the queue in the order s _ú_ a b c _ú_ d f _ú_ d **e** _ú_ d _ú_ _ú_" and from the fourth phase on the green arrow: "d **e** _ú_ ". Considering ú is the end-of-phase token.

**Comment by jeffgerickson** [comment]
Good catch!
