### ISSUE TITLE
[Oops.] Ch. 6 Problem 0(e)

### ISSUE THREAD

**Issue by hsinhao** [jeffgerickson/algorithms#126]
**Please verify that the error is present in the most recent revision before reporting.**

**Chapter number or note title:** Ch. 6

**Page number:** 20

**Error description:** The statement in problem 0(e) seems to be incorrect. 
https://photos.app.goo.gl/AqfCA2kJa2ZjTBTc8
In the example in the link, if we perform a DFS starting at 1, we could have f(3) < f(6) < f(2).

**Suggested fix (if any):**

**Comment by jeffgerickson** [comment]
Figure 6.14 is another counterexample.

**Comment by jeffgerickson** [comment]
Removed.  (I could add the qualifier "such that S cannot reach T and T cannot reach S in scc(G)", but that seems awkward.)
