### ISSUE TITLE
[Oops.] Error in Figure 11.2 (bipartite graph example)

### ISSUE THREAD

**Issue by kingdish** [jeffgerickson/algorithms#127]
**Please verify that the error is present in the most recent revision before reporting.**

**Chapter number or note title:** Figure 11.2. A maximum matching in a bipartite graph G, and the corresponding maximum flow in G′.

**Page number:** 356

**Error description:** In Figure 11.2, the maximum matching / max flow should be 6.
We can push flows in the following order to get a max flow of 6:
[1, 2]
[2, 5]
[3, 4]
[4, 1]
[5, 3]
[6, 7]

**Suggested fix (if any):** Update the example

**Comment by jeffgerickson** [comment]
[Add picture of alternating path at bottom of page.]

**Comment by jeffgerickson** [comment]
Fixed and added figure showing a sequence of matchings and alternating paths.
