### ISSUE TITLE
[Oops.] Ch. 6 Problem 15

### ISSUE THREAD

**Issue by TinfoilHat0** [jeffgerickson/algorithms#128]
**Please verify that the error is present in the most recent revision before reporting.**

**Chapter number or note title:** [title] Ch 6, Problem 15
 
**Page number:** [page] 27

**Error description:** [error] In problem description, weights are assigned to the edges however, _interval weight_ is defined as sum of the weights of vertices.

**Suggested fix (if any):** [fix]

**Comment by jeffgerickson** [comment]
Weighted vertices, not weighted edges.
