### ISSUE TITLE
Please improve contrast in colorized figures

### ISSUE THREAD

**Issue by echuber2** [jeffgerickson/algorithms#130]
Some figures (such as the DFS/BFS examples on page 202) use color in such a way that is difficult for some readers to differentiate.

Suggestions (any or all of these):

- Use colors with a high perceived lightness to contrast against dark backgrounds.
- Make solid black lines dotted or dashed to improve contrast with solid colored lines.
- Proof pages with filters simulating forms of color blindness to preview the effect.
- Combine color with some other distinguishing feature such as line stroke pattern or fill pattern as a distinguishing feature. (For example, Fig. 5.8 (p 194), the Tower of Hanoi configuration graph, is very hard to discern.)

**Comment by echuber2** [comment]
[Also wondering, not just for this textbook, but for other courses' materials] what would be the most effective way to provide alt-text for graphs in PDFs, especially for students who have totally impaired vision.

**Comment by jeffgerickson** [comment]
I've already tried to do this in several places.  For example, for the examples on page 202, the tree edges are not just blue but also 3 times as wide as the non-tree edges.  Any example that uses color explicitly as a label (like 3-coloring graphs) uses different symbols/line weights, etc.

In other places, the color is not really necessary to understand the figure (like Figure 5.8).

My next editing pass will be from a black and white proof, simulating the eventual printed copy, but it would be helpful to have an explicit list of figures that need improvement.

**Comment by jeffgerickson** [comment]
LaTeX is completely horrible for accessibility.  The best answer on tex.stackexchange (from 2012) suggesting using the `pdfcomment` package to add "tool tips"/alt-text to figures, which should be relatively straightforward, but only God knows how a screen reader would read something like Figure 1.9, or Exercise 1.41 (p66), or the examples on page 82 and 89, or the LISBigger recurrence on p109, or the edit sequences on p116, or the footnote on p.165, or....

**Comment by echuber2** [comment]
I see, thank you. About the screen reader issue, I heard from a College of Business media director that many screen reader users find alt text annoying, at least in how it's usually set up (vaguely suggesting what a figure contains, and just adding noise to page navigation). So it was suggested that rather than alt text, the explicit figure captions could very specifically narrate what the figure depicts, like the descriptive audio track on a movie. I guess this would lead to all figure captions taking up a good amount of space. In that case it might make more sense to just weave an explicit description into the body text.

It sounds like there are some attempts to make web-based documents navigable according to ARIA guidelines in a way that figures could be expanded or collapsed, but nothing has consistent support. I imagine there needs to be some way to provide semantic markup for all kinds of figures in a way that can be navigated. Barring that, I'm going to try to write verbose captions everywhere for the time being.

**Comment by jeffgerickson** [comment]
After further thought, I've decided to close this one as too broad/open-ended.  If there are specific figures (or types of figures) that need improvement, please open a separate issue for each one, with specific suggestions for improvement.

**Comment by echuber2** [comment]
Fair enough! (I actually had difficulty myself discerning the blue-back graph on page 202, at least on my janky laptop screen.)
