### ISSUE TITLE
[Oops.] Possible mistake lemma 8.3's proof

### ISSUE THREAD

**Issue by jamartinec** [jeffgerickson/algorithms#141]
**Please verify that the error is present in the most recent revision before reporting.**
Link: http://jeffe.cs.illinois.edu/teaching/algorithms/book/Algorithms-JeffE-2up.pdf

**Chapter number or note title:** [Shortest Paths]

**Page number:** [286]

**Error description:** [I think there's no reason to say that there's an edge between the u_i and u_{i+1} nodes. I

**Suggested fix (if any):** [ think it would be clearer if two cases were considered:
1) u_{i+1} is a neighbor of u_i. In that case dist(u_{i+1}) was updated during iteration i, and the relaxation of the arc implies d_{i+1}\geq d_{i}.
2) u_{i+1} is not a neighbour of u_i, so ú_{i+1} was already in the priority row before iteration i, and we know then that d_{i+1} \geq d_i.]

Apologies beforehand, if I'm wrong

**Comment by jeffgerickson** [comment]
You're right, this should be clarified.  But I'm consistently using "relaxing an edge" to mean _changing_ the distance at the head, so the proposed fix isn't quite correct either.  Even if u_{i+1} is a neighbor of u_i, the value of dist(u_{i+1}) may not change during iteration i.

**Comment by jeffgerickson** [comment]
Changed to the following.  (I think this is a little clunky, so I may edit further.)

<img width="548" alt="Screen Shot 2019-05-14 at 12 27 41 PM" src="https://user-images.githubusercontent.com/2807510/57691158-b3075780-7643-11e9-8ab9-50933e828709.png">
