### ISSUE TITLE
"Disjoint Sets" link - 404 Not Found

### ISSUE THREAD

**Issue by kindkid** [jeffgerickson/algorithms#18]
At http://jeffe.cs.illinois.edu/teaching/algorithms/, there is a link "Disjoint Sets" with href="notes/11-union-find.pdf", which currently results in a "404 Not Found" error message.

**Comment by hutualive** [comment]
I met similar issue too, the URL is 404(http://jeffe.cs.illinois.edu/teaching/algorithms/notes/11-union-find.pdf). either a typing error or file is not exist.

**Comment by gilbertguan2385** [comment]
Same issue too,(http://jeffe.cs.illinois.edu/teaching/algorithms/notes/11-union-find.pdf) NOT FOUND.

**Comment by hutualive** [comment]
@daveinnyc thanks. it's working 👍

**Comment by gilbertguan2385** [comment]
@daveinnyc Thanks a lot.
