### ISSUE TITLE
Edit Distance Memo Table Query

### ISSUE THREAD

**Issue by philmolyneux** [jeffgerickson/algorithms#19]
Page 113 has the edit distance memo table for ALGORITHM to ALTRUISTIC - the entry for ALGORIT to ALT has a cost of 4 with both a free replacement and a deletion from a cost of 4 - should the deletion arrow be there ? I very much like your notes and have been using them for a couple of years (with attribution) - I recalculated the table and my version is on my slide 108/142 of http://www.pmolyneux.co.uk/OU/M269/M269TutorialNotes/M269TutorialGraphs/M269TutorialGraphs2017J.beamer.pdf - it looks like your notes are produced in LaTeX - I used LaTeX with the PGF/TikZ package to typeset the table (though I used Haskell to calculate the PGF/TikZ for the table)

**Comment by jeffgerickson** [comment]
You're right; that arrow shouldn't be there.
