### ISSUE TITLE
Ch. 0 section 3 pg. 9: possible error in Huntington-Hill pseudocode

### ISSUE THREAD

**Issue by markstegeman** [jeffgerickson/algorithms#21]
I understand the pseudocode as follows:

The first `for` allocates _n_ representatives, and decreases _R_ by _n_ (I'll call this _R' = R - n_).
The second `for` runs from _n+1_ to _R'_, i.e. it allocates _R - 2n_ representatives.

The total number of representatives allocated is then only _R - n_.

**Comment by echuber2** [comment]
I think you're right. The `R ← R - 1` line might need to be removed. https://www.census.gov/topics/public-sector/congressional-apportionment/about/computing.html
