### ISSUE TITLE
typos in preface

### ISSUE THREAD

**Issue by davidlowryduda** [jeffgerickson/algorithms#27]
pg iv:

    the goal of these problems not to solve these particular problems,
    but to practice exercising a particular skill

wants to have `is` between `problems` and `not to`.

I'll add more typos to this issue as I find them. Thank you for your book.

Unrelatedly: is there a chance you would share the source files for the book?

**Comment by davidlowryduda** [comment]
Yeah, I understand. And I think that perhaps keeping clean latex is hard enough on its own. But on the other hand, I would feel comfortable submitting typo fixes as pull requests, which might save you some time for small little things like these. So of course I say "Don't worry about the mess!" (But I still clean up a little bit before inviting others to my house too).

**Comment by jeffgerickson** [comment]
Typo fixed: "These exercises are designed as opportunities to practice, not as targets for their own sake; the goal is not to solve these particular problems, but to practice exercising a particular set of skills, or solving a \emph{type} of problem."

**Comment by jeffgerickson** [comment]
Better: "The goal of each problem is not to solve that specific problem, but to exercise a certain set of skills, or to practice solving a certain \emph{type} of problem."
