### ISSUE TITLE
Kosaraju's algorithm is mistyped as "Koraraju"

### ISSUE THREAD

**Issue by jogloran** [jeffgerickson/algorithms#29]
In Chapter 6, "Depth-First Search", in the section "Koraraju and Sharir’s Algorithm", Kosaraju's name is misspelt in the title and body text as "Koraraju". 

(The footnote on the first page of the section, however, as well as the algorithm pseudocode itself, has the correct spelling for the name.)

**Comment by jeffgerickson** [comment]
I really need to reset my spelling dictionary.
