### ISSUE TITLE
Typos in Introduction

### ISSUE THREAD

**Issue by tallforasmurf** [jeffgerickson/algorithms#30]
Footnote 9, missing period.

I'll add any more if I notice them.

Or anybody else is welcome to comment. Why perhaps do you not open a set of Issues "Typos in <chapter>" and let people comment?

Top of page 14, " (Slide) " appears to be an extraneous remnant. Or a joke I don't get?

**Comment by plin25** [comment]
> Why perhaps do you not open a set of Issues "Typos in " and let people comment?

That was my intent with [issue 7](https://github.com/jeffgerickson/algorithms/issues/7) but only one other person commented in it.

![image](https://imgs.xkcd.com/comics/standards.png)

**Comment by jeffgerickson** [comment]
Footnote 9 is not a sentence, so the missing period is correct.
