### ISSUE TITLE
Chapter 1 Section 5 Page 29 possible error in quicksort partition pseudocode

### ISSUE THREAD

**Issue by viamodulo** [jeffgerickson/algorithms#32]
I believe the last swap in the partition pseudocode should be : 
swap A[ n ] <-> A[ l + 1 ] 
since the pivot is set to the back of the array and not the front

![image](https://user-images.githubusercontent.com/7672474/50650395-9580fd80-0f80-11e9-8fc8-1c248fcfd2a4.png)

**Comment by jeffgerickson** [comment]
Oops!  Yes, you're right.

**Comment by tejaslodaya** [comment]
True. Just encountered the error and came here to open an issue!
