### ISSUE TITLE
Chapter 5, p.22, Exercise 6(a) -- a minor issue.

### ISSUE THREAD

**Issue by bshk003** [jeffgerickson/algorithms#35]
The following seems like a definition of a Hamiltonian path, rather than a cycle, since in the latter case the starting/terminal vertex gets visited twice.

_A Hamiltonian cycle in a graph G is a cycle of edges in G that visits every vertex of G **exactly once**_

**Comment by jeffgerickson** [comment]
Hmm.  Cycles don't really have "starting" vertices.  (But then I'm defining cycle incorrectly in Chapter 5!)

**Comment by jeffgerickson** [comment]
Changed "visits" to "enters" to remove any ambiguity.
