### ISSUE TITLE
Chapter 2, p. 86 - Copy/paste error in pseudocode

### ISSUE THREAD

**Issue by eugene-bulkin** [jeffgerickson/algorithms#38]
In the updated `LISBigger` pseudocode that uses indices instead of arrays, the `else if` block is using the same code as the previous version:

```
...
else if A[1] <= prev
...
```

when it should be using the new version:

```
...
else if A[i] >= A[j]
...
```

as per the piece-wise function definition.

**Comment by sinette** [comment]
In addition to my earlier comment
