### ISSUE TITLE
Minor Typos on Pages 26, 29, and 30

### ISSUE THREAD

**Issue by TimSevereijns** [jeffgerickson/algorithms#40]
The following typos appear in the 0th edition, dated December 29, 2018:

- In the footnote on page 26, I believe it should read:
    - "...because the EDVAC could sort faster **than** IBM’s dedicated sorters..."
- On page 29, I think it should probably read: 
   - "In the separate `Partition` subroutine, the input parameter `p` is **the** index of the pivot element..."
- On page 30, it should probably read:
   - "...and take the median of those three elements **as** the pivot."

**Comment by jeffgerickson** [comment]
Check, check, check.
