### ISSUE TITLE
Typo in German quote in section 2.1

### ISSUE THREAD

**Issue by paulbaumgart** [jeffgerickson/algorithms#43]
In the Gauss quote in section 2.1, the German word [Gewissheit](https://en.wiktionary.org/wiki/Gewissheit#German) is misspelled as `Gewifsheit`, presumably due to a mis-transliteration of a [long s (ſ)](https://en.wikipedia.org/wiki/Long_s) into an `f`.

In modern German, the world is spelled with a double short s: `Gewissheit`.

**Comment by jeffgerickson** [comment]
Thankſ!

**Comment by sten13** [comment]
Alternatively, this could be a nod to Terry Pratchett, who did this regularly (and deliberately) for comic effect.

**Comment by jeffgerickson** [comment]
I'll correct this to "Gewissheit", but I have to wonder whether "Gewißheit" would be more accurate.

**Comment by jeffgerickson** [comment]
Nope.  According to Peters's 1865 collection of Gauss's letters to Schumacher, it's a double short-s.

<img width="1075" alt="PPN63510394X pdf (page 124 of 134)-1" src="https://user-images.githubusercontent.com/2807510/54344923-3c99a980-4642-11e9-8639-af68942ad7b1.png">

<img width="1019" alt="PPN63510394X pdf (page 122 of 134)" src="https://user-images.githubusercontent.com/2807510/54344650-9f3e7580-4641-11e9-92e0-6c4a39d1159a.png">

<img width="836" alt="PPN63510394X pdf (page 124 of 134)" src="https://user-images.githubusercontent.com/2807510/54344738-d3199b00-4641-11e9-9287-f4a1a4519d84.png">

**Comment by jeffgerickson** [comment]
Also corrected "Tatonneiren" to "Tatonniren"!
