### ISSUE TITLE
Missing word in 4.5 Stable Matching, page 170

### ISSUE THREAD

**Issue by kipras** [jeffgerickson/algorithms#44]
In Greedy Algorithms, 4.5 Stable Matching, section "Some Bad Ideas", page 170

At the top of the page:
```
Unfortunately, resolving one instability can new ones
```

Should probably be "can **create** new ones" or such.

**Comment by kipras** [comment]
A few more cosmetic things:

2.7 Longest Increasing Subsequence, Take 2, page 87

> Is A[i] is the next element of the output sequence?

Second"is" is unnecessary.

----

7.2 The Only Minimum Spanning Tree Algorithm, page 257
> An edge is safe if it is the minimum-weight edge with with exactly one endpoint in some component of F.

"with" repeats twice

----

7.5 Kruskal’s Algorithm, page 265

> More generally, Kruskal’s algorithm maintains a partition of the the vertices of G into disjoint subsets

"the" repeats twice

----

9.4 Johnson’s Algorithm, page 310

> These new weights non-negative because Bellman-Ford halted!

Should probably be "weights are non-negative"

----

9.6 Divide and Conquer, page 313

> This idea gives us a different recurrence for same the function dist(u, v, l)

"same" and "the" should probably be swapped.

----

Great book by the way! :)

**Comment by jeffgerickson** [comment]
Check, check, check, check, check, check, thanks!
