### ISSUE TITLE
Ch. 1 section 3 pg. 25: Tower of Hanoi

### ISSUE THREAD

**Issue by lodayatejas** [jeffgerickson/algorithms#45]
In the second paragraph, it says 

> We can’t move it at the beginning, because all the other disks are in the way. So first we have to move those n−1 disks to the **third peg**

It's actually, move those n-1 disks to the **second peg**

All the extra n-1 disks have to be moved to second peg, the largest n<sup>th</sup> disk has to be moved to the 3rd peg and all n-1 disks have to be moved on top of the n<sup>th</sup> disk in 3rd peg.

**Comment by jeffgerickson** [comment]
(Clarify "second" and "third" in surrounding text.)

**Comment by lodayatejas** [comment]
second -> `tmp`
third -> `dst`

So, first we have to move those n-1 disks to `tmp` peg, n<sup>th</sup> disk to `dst` peg and then n-1 disks from `tmp` peg to `dst` peg.

Let me know if it makes sense.
The diagram and the pseudocode are correct, but description is a little wrong.

**Comment by jeffgerickson** [comment]
No, I'm not going to use `tmp` and `dst`.  I'm writing in English, using English words.

**Comment by echuber2** [comment]
@lodayatejas I think what Prof. Erickson wrote above about "Clarify..." was just his note to himself for making the revision later. :-)

@jeffgerickson I think he thought you were asking for clarifications.

**Comment by lodayatejas** [comment]
@echuber2 You got me.
No confusion anymore.

**Comment by jeffgerickson** [comment]
Replaced "third" with "spare".

**Comment by lodayatejas** [comment]
@jeffgerickson Thanks! I'll go ahead and close the ticket
