### ISSUE TITLE
Chap 2.7 LISfirst should return 1 for n

### ISSUE THREAD

**Issue by dracodoc** [jeffgerickson/algorithms#57]
Chap 2.7, p 88 has base case of `LISfirst(n) = 1`. However the code below seemed to have `best` initialized as 0. Then with `i = n` it will return 0.

**Comment by jeffgerickson** [comment]
replaced last line with "return 1 + _best_"

**Comment by jeffgerickson** [comment]
<img width="578" alt="02-backtracking pdf" src="https://user-images.githubusercontent.com/2807510/53958508-87b33a00-40e1-11e9-8499-d8b4b52b9873.png">
