### ISSUE TITLE
Typos in Chapter 2; pages 71, 74, 76, 82, & 83

### ISSUE THREAD

**Issue by TimSevereijns** [jeffgerickson/algorithms#59]
The following is in reference to the 0th Edition, dated Dec. 29th, 2018.

* On page 71, I believe it should read:
   * "Each node in this tree corresponds to **a** recursive subproblem,..."
* On page 74, I believe it should read:
   * "...because **the** empty set is a subset of..."
* On page 76, the follow reads a bit awkwardly:
   * "...but in fact the running time is still `O(n)` even if adding an element to `Y` in the second-to-last time requires `O(|Y|)` time."
   * Should the second "in" be "for" instead?
   * Consider the word "penultimate" instead of "second-to-last".
* On page 82, it should read:
  * "Because we don't know what ~~what~~ `IsWord` is doing,..."
* On page 83, it should probably read:
   * "...we might assign higher scores to longer and/or more frequent words, and lower **or** negative scores to longer and/or more ridiculous non-words."

**Comment by jeffgerickson** [comment]
"in the second-to-last **time**" -> "in the second-to-last **line**"

**Comment by jeffgerickson** [comment]
I rewrote the offending sentence on page 76.

"This algorithm also runs in $O(2^n)$ time; the analysis is simplest if we assume a set data structure that allows us to insert a single element in $O(1)$ time (for example, a linked list), but in fact the running time is still $O(2^n)$ even if insertion requires $O(n)$ time (for example, a \emph{sorted} linked list)."

(The sentence was referring to pseudocode in an earlier version that I removed.)

**Comment by jeffgerickson** [comment]
Rewrite sentence on page 83:

"For example, we might assign higher scores to longer or more common words, lower scores to shorter or more obscure words, slightly negative scores for minor spelling errors, and more negative scores to obvious non-words."
