### ISSUE TITLE
Definition/Description of Algorithm in 0.1 misses finiteness as a necessary condition.

### ISSUE THREAD

**Issue by swapnilb** [jeffgerickson/algorithms#6]
In sec. 0.1, an algorithm is informally defined, described. It lists a set of conditions for it including unambiguousness, precision, etc. of instructions.

But it does not list finiteness of the sequence of instructions as a necessary condition.

I think this is not consistent with how algorithms are defined and understood in the CS community. They are defined, among other things, to be finite sequences of instructions.

Therefore, I think the list of conditions should be amended to include finiteness as a necessary condition.

Thanks.

**Comment by jeffgerickson** [comment]
I'm not convinced that "finiteness" _should_ be included in the definition of "algorithm", which is why I omitted it.  For (almost) every problem considered in the book, finiteness is implicit in the requirement that the algorithm actually solves the problem (meaning it actually returns an answer) and in my insistence on worst-case time analysis. I don't see any point in emphasizing it.

But algorithms that never terminate are endemic in operating systems: time-slicing, processor scheduling, paging, caching, garbage collection, load balancing, network routing, window/screen management, and so on.  (I actually consider garbage collection in the exercises in Chapter 5.) And it's a matter of pedagogical emphasis whether _abstract_ numerical algorithms that converge to an answer (like Mesopotamian square roots, or the ellipsoid method for real-valued LPs) _actually_ halt in finite time; I prefer to believe that the finite patience of human beings forces us to terminate them before they're done.

I'm willing to be convinced, so I'll leave this open for now.  But "everybody does it this way" is not going to convince me.

**Comment by swapnilb** [comment]
I think you're conflating length of execution with length of algorithm.

I am talking about the latter: an algorithm is a finite sequence of unambiguous instructions. A list of infinite length is not an algorithm.

I am not talking about it's execution length, or to be more precise, the length of a computation.

**Comment by jeffgerickson** [comment]
Sorry, I misunderstood you.  Yes, I agree that the finiteness of the algorithm itself is crucial for the definition.

But then isn't "finite" already implied by "explicit"? After all, you can't actually _write down_ an infinite sequence of instructions.

On the other hand, even though "finite" is redundant, is it useful redundancy?  Hmm.

**Comment by jeffgerickson** [comment]
I can (in principle) write a finite C program that generates an infinite sequence of Python instructions, and then (in parallel) runs a Python interpreter to execution of that infinite code _as if it were_ explicitly written down. Then the C program **is** (an implementation of) an algorithm, but the infinite Python code that the C program is writing and interpreting **is not** (an implementation of) an algorithm?  Weird.

[[Insert further pointless philosophical digressions about self-modifying code here.]]

**Comment by swapnilb** [comment]
Do you mean to exclude implicitly described finite sequences of instructions?
But they are valid algorithms. So using "explicit" excludes things that I suspect you'd want to include.

Using "finite" doesn't have that disadvantage.

**Comment by echuber2** [comment]
It sounds like arguably, you can have a sequence of instructions that's implicit and infinite.

**Comment by swapnilb** [comment]
To summarize, the question asked was: is explicit the same as finite -- do we lose anything if we just say explicit instead of finite?

The question I asked in response was: what if you have an implicitly described finite set of instructions? We wouldn't want to exclude that from the definition of an algorithm, because that is a valid algorithm, even if it is implicitly defined.

(There is no proposal for an implicit infinite set of instructions. An infinite list of instructions (implicit or explicit) is not covered by the standard definition of an algorithm.) So, I probably don't understand the last comment by @echuber2.

**Comment by echuber2** [comment]
@swapnilb Well I'm being a bit facetious, but I'm referring to the philosophical digression about self-mutating programs that Prof. Erickson raised. Perhaps the standard definition is too narrow or the introduction could simply add a few words to acknowledge such an edge case.

**Comment by jeffgerickson** [comment]
> what if you have an implicitly described finite set of instructions? We wouldn't want to exclude that from the definition of an algorithm

Actually yes, I _would_ want to exclude that from the definition of an algorithm.  For example:
```
if the 31337th busy beaver number is divisible by 42
     return true
else
     return false
```
is definitely **NOT** an algorithm, even though it is unambiguously an implicit representation of one of the trivial algorithms "return true" or "return false".  It's only an algorithm if it **can** be written down explicitly.

**Comment by jeffgerickson** [comment]
(And the introduction is really not a good place to discuss edge cases.)

**Comment by jeffgerickson** [comment]
See also: If you haven't written down a proof, it isn't a theorem yet.

**Comment by swapnilb** [comment]
Then you should probably call this discrepancy out. What you call an algorithm is different from what the CS community considers an algorithm. 

I agree -- an introduction is not a good place to miscommunicate a definition central to your book.
It is best to write it down in its own section.

**Comment by jeffgerickson** [comment]
As a decades-long card-carrying professional member of the computer science community, I strongly disagree with the contention that what I consider to be an algorithm is different from what the computer science community considers to be an algorithm.
