### ISSUE TITLE
Chapter 3, Section 3.1, Page 5, footnote is incomplete

### ISSUE THREAD

**Issue by zhangyaqi1989** [jeffgerickson/algorithms#62]
The current footnote of page 5 (in the whole book the page is 99) reads as

> ... as part of their code-breaking efforts at

This is incomplete. A possible fix is 

> ... as part of their code-breaking efforts at England in World War II.

**Comment by jeffgerickson** [comment]
As Tim says, the footnote is longer than the vertical space below the footnote marker, so the footnote overflows onto the next page.  This is standard in European typography.  It might be clearer to move everything onto page 100, but that would leave a large blank space at the bottom of page 99.
