### ISSUE TITLE
organization issue in Chapter 5, page 10

### ISSUE THREAD

**Issue by hundredeir** [jeffgerickson/algorithms#63]
Second paragraph talks about adjacency matrix whereas adjacency matrix topic's heading is next and isn't yet talked about.

**Comment by jeffgerickson** [comment]
An adjacency array (described in the second paragraph on page 10) is **not** the same as an adjacency matrix, despite the similarity of the names.

**Comment by hundredeir** [comment]
![image](https://user-images.githubusercontent.com/20334754/51077131-ffdd2080-1699-11e9-8795-c23b9abe2ed9.png)

Maybe then it's a case of typo

**Comment by echuber2** [comment]
I second that it's probably a typo; it probably should say "One common implementation of adjacency _lists_ is the adjacency array."

**Comment by echuber2** [comment]
For what it's worth, bump @jeffgerickson
