### ISSUE TITLE
Ch0.6 p15 NDaysOfChristmas

### ISSUE THREAD

**Issue by MarkJeronimus** [jeffgerickson/algorithms#67]
The running time should probably be Θ(2), not Θ(3)

**Comment by jeffgerickson** [comment]
That's what it says on page 15:  "It’s quite easy to show that **the singing time** is Θ(n^2); in particular, the singer mentions the name of a gift n(n + 1)/2 times (counting the partridge in the pear tree)."  But the **number of gifts** is Θ(n^3).
