### ISSUE TITLE
Ch2.2 redundant (or redundant) statement

### ISSUE THREAD

**Issue by MarkJeronimus** [jeffgerickson/algorithms#69]
"obviously (or “obviously”)" is either redundant or incorrect (the issue's title is a pun on this).

**Comment by echuber2** [comment]
It's just tongue-in-cheek humor. Prof. Erickson criticizes the overuse of words like "obviously" especially where they're not warranted. You can see a few more places in the book where it's written with mocking quotation marks.

See also the footnote on ex. 10.17, or the "deadly sins" from his spring 2018 course: https://courses.engr.illinois.edu/cs374/sp2018/A/hw-policies.html#sins

**Comment by echuber2** [comment]
...more to the point, Ch. 0 talks about clear writing and "obviously" in several places.
