### ISSUE TITLE
Minor typos in commit fbf5aea (and bc54407)

### ISSUE THREAD

**Issue by plin25** [jeffgerickson/algorithms#7]
The following typos exist in [fbf5aea](https://github.com/jeffgerickson/algorithms/commit/fbf5aeab659cb3f7312a4c7476f44cb8d15e2543) and therefore also in the B&W [bc54407](https://github.com/jeffgerickson/algorithms/commit/bc54407506508a7684989082750488979ed01b0b).

Page 226 of the main book (§6.1): The first sentence of the first paragraph under the pseudocode for `Preprocess`, `PreVisit`, and `PostVisit` reads "This algorithm assigns v.pre (and advance the clock)": "advance" should be "advances". A similar typo exists later in the sentence after v.post.

Page 257 of the main book (§7.2): The last bullet point has a duplicated word "An edge is safe if it is the minimum-weight edge **with with** exactly one".

(These two typos are right next to typos found in [my previous typos issue](https://github.com/jeffgerickson/algorithms/issues/2) too! Ugh!)

**Comment by plin25** [comment]
Page 258 (§7.2): the prime in the label of Figure 7.2 is a smart quote instead of an actual prime.

**Comment by plin25** [comment]
Page 15 (§0.6): second line ends with "Not in this **class** ", should class be book?

**Comment by plin25** [comment]
Page 26 (§1.3): last paragraph before §1.4, third to last line: "plus de cinq **millards** de siècles" "millards" -> "milliards"

**Comment by echuber2** [comment]
Ch. 12, ex. 39, p. 424: "Proper etiquette dictates that each marcher must know the person directly in front of them in line, lest a minor mistake during lead to horrible embarrassment between strangers."

It seems a word is missing between "during" and "lead."

**Comment by jeffgerickson** [comment]
- §6.1: advance -> advances (twice) ✓
- §7.2: with with -> with ✓
- Figure 7.2: e’ -> e' ✓
- §0.6: class -> book ✓
- §1.3: millards -> milliards
- Ex 12.39: removed "during"
