### ISSUE TITLE
Chapter 5: Computatio Canonica

### ISSUE THREAD

**Issue by TimSevereijns** [jeffgerickson/algorithms#70]
The following is in reference to the 0th Edition, dated Dec. 29th, 2018

On page 186, it reads:

> Where the Roman computatio legalis required the sum of
the distances to the nearest common ancestor to be at least four, the newer
computatio canonica required the maximum of the two distances to be at least
seven.

I think the church would have preferred the minimum of the two distances instead. :smile:

**Comment by jeffgerickson** [comment]
No, I'm pretty sure _maximum_ is correct; they wanted at least seven degrees of separation, not at least fourteen.  But let me check my sources again.

**Comment by jeffgerickson** [comment]
Indeed, it's the maximum.  See http://www.newadvent.org/cathen/04264a.htm:

> In the direct line the Roman civil and the canon law agree on the principle that there are as many degrees as generations; hence as many degrees as there are persons, omitting the stock or root. A son is one degree from his father, a grandchild two degrees from the grandfather. In the computation of the degrees of the transverse or collateral line there is a serious difference between the Roman civil and the canon law. The civil law founded its degrees upon the number of generations, the number of degrees being equal to the number of generations; thus between brothers there are two degrees as there are two generations; between first cousins four degrees, corresponding to the four generations. The degrees are calculated easily in the civil law by summing up the number of persons in each line, omitting the common ancestor. Except for marriage, the canon law follows regularly the computation of the civil law, e.g. in the question of inheritance. But the Canon law, in the collateral line of consanguinity, computes for marriage one series only of generations, and if the series are unequal, **only the longer one**. Hence the principle of canon law that in the transverse or collateral line there are as many degrees of consanguinity as there are persons in the longer series, omitting the common stock or root.

**Comment by TimSevereijns** [comment]
Ah, I see. I misread the sentence as meaning that the distance to the nearest common ancestor could be at most seven.

Thanks for the clarification. Feel free to close the issue.
