### ISSUE TITLE
Ch2.4 note6 p78 Go should be capitalized

### ISSUE THREAD

**Issue by MarkJeronimus** [jeffgerickson/algorithms#73]
"Chinese rules for go"

'Go' is the name of the board game so it should be capitalized.

**Comment by echuber2** [comment]
It seems that "Go" is often capitalized to distinguish from the English verb "go" according to Wikipedia, but I hadn't actually paid attention to the distinction before myself. Note that common/ancient board games like backgammon and chess, and some card games like poker, and sporting games in general like basketball, are often _not_ capitalized unless they're part of a proper noun.

**Comment by jeffgerickson** [comment]
What Eric said.  Lower-case "go" seems to be standard among professional go players.  More generally, the standard I'm used to is that _common_ games like checkers, draughts, nine men's morris, backgammon, bridge, blackjack, roulette, solitaire, tic-tac-toe, rock-paper-scissors, mancala, shogi, and senet are treated like _common_ nouns.  Games that are always capitalized are either brand names/trademarks (Monopoly, Scrabble, Hungry Hungry Hippos) or involve proper nouns (Texas Hold 'Em, Klondike).  Compare reversi with Othello, or gomoku with Pente.

See also:
- https://www.quora.com/Is-the-board-game-Go-go-capitalized
- https://english.stackexchange.com/questions/8126/is-the-game-go-a-proper-noun-what-about-checkers-or-chess
- https://boardgamegeek.com/thread/946114/should-game-names-be-capitalized
