### ISSUE TITLE
[Oops.]

### ISSUE THREAD

**Issue by zx9w** [jeffgerickson/algorithms#78]
* Please verify that the error is present in the most recent revision before reporting --- Check
* For errors in the book, please indicate the chapter and page number --- Check
* For errors in the notes, please indicate the note title and page number --- Check
* In both cases, please describe the bug in detail, and if possible, suggest a correction. --- Check (the implicit suggestion is to fix it)

Page 29 in book or page 9 in chapter 1.

There is a fancy L in the word less:

The variable -fancy L- counts the number of items in the array that are less <- the problem is in this word.

**Comment by plin25** [comment]
This is probably intentional, to tie the variable to the meaning.
