### ISSUE TITLE
French in Alouette algorithm

### ISSUE THREAD

**Issue by fsikora** [jeffgerickson/algorithms#8]
Hi,

in 0.6, algorithm for Alouette, the french is clumsy.

Plumerais -> plumerai, 3 times (future https://leconjugueur.lefigaro.fr/conjugaison/verbe/plumer.html)
\'a -> à, 2 times (other direction)
\'a bas \'a -> à
inner loop: i-1 -> i (I think you have to re-sing the introduced part, cf https://en.wikipedia.org/wiki/Alouette_(song) )

Thanks,
Florian

**Comment by jeffgerickson** [comment]
🤦‍♂️Eh bien, je suis gêné!

**Comment by jeffgerickson** [comment]
Better?

<img width="1328" alt="00-intro pdf page 16 of 20" src="https://user-images.githubusercontent.com/2807510/53876071-50bc2600-4006-11e9-86b1-9622d137b396.png">

**Comment by fsikora** [comment]
Great! Thanks.
