### ISSUE TITLE
Typo: Memorization misspelled as memoization throughout the book.

### ISSUE THREAD

**Issue by maximxue** [jeffgerickson/algorithms#81]
Typo: Memorization misspelled as memoization throughout the book.

**Comment by jeffgerickson** [comment]
This is not a typo.  See the footnote on page 98.

(Wikipedia is actually incorrect on this point; Michie never used the word himself.)

**Comment by jeffgerickson** [comment]
...but perhaps I should add a parenthetical "(without an r)" or "(sic)".
