### ISSUE TITLE
Ch 0 Exercise 4.a (Huntington-Hill) error

### ISSUE THREAD

**Issue by Omicron18** [jeffgerickson/algorithms#85]
Exercise says: "Prove that r[i] >= floor (r*_i) for all i"

This doesn't seem always to be true.  Set R=4, n=3, P[1]=10, P[2]=P[3]=1.  Then the algorithm clearly gives r[1]=2, r[2]=r[3]=1.  But r*_1 = 4 * 10/12 = 3.3333, so floor (r*_1) = 3 > 2.

**Comment by Omicron18** [comment]
Incidentally, it's nowhere explicitly stated that R must be greater than n.  And the notation is slightly inconsistent between Figure 0.5 and Exercise 4: Pop[i] and Rep[i] vs P[i] and R[i], though I guess that's another issue.

**Comment by jeffgerickson** [comment]
Rewritten.

<img width="367" alt="00-intro pdf page 19 of 20" src="https://user-images.githubusercontent.com/2807510/53942825-1614c500-40bc-11e9-9ac0-fb81b3061a15.png">

**Comment by jeffgerickson** [comment]
I also fixed "that that" in the second paragraph.
