### ISSUE TITLE
Possible error in the Huffman code example

### ISSUE THREAD

**Issue by filipmaric** [jeffgerickson/algorithms#86]
**Chapter number or note title:** 4.4. Huffman codes

**Page number:** 165

**Error description:** I have implemented Huffman code encoder and it reported that the minimal number of bits is 649 instead of 646. In the tree shown on the figure 17 should be paired with 21 instead of 22 (letter T), and this error propagates further to the top of the tree. Depth of the letter O is 5 instead of 4, so the table also contains an error wrt. the given tree.

**Comment by jeffgerickson** [comment]
Need to double-check myself

**Comment by julianoch** [comment]
Seconded! My intuition behind this is that the numbers at any level must be larger or equal to those at the next level. This can be proved using an exchange argument. For example if we exchange nodes T with the node containing the sum 16, we are sure to get a full binary tree with a better overall cost.

**Comment by jeffgerickson** [comment]
Double-checked.  @filipmaric is correct that 17 should be paired with 21, not 22.  The correct number of bits for the message is **643**.

<img width="1114" alt="04-greedy pdf" src="https://user-images.githubusercontent.com/2807510/53875266-71837c00-4004-11e9-886d-d49bea9d5204.png">

(The minimum cost 649 that @filipmaric reports cannot be correct, because that's _more_ than the cost 646 of the code in the text!)

**Comment by erbenpeter** [comment]
I also implemented the Huffman-code algorithm, and also got 649 for the optimal length. My per letter bit lengths are:

```python
{
  'n': 3, 'h': 4, 'w': 4, 'x': 5, 
  'l': 6, 'u': 6, 'o': 4, 'y': 5, 
  'f': 5, 'v': 5, 'r': 5, 't': 3, 
  'c': 6, 'a': 6, 'g': 6, 'z': 7, 
  'd': 7, 'i': 4, 'e': 3, 's': 3
}
```

My generated tree (in bracketed notation):

```
(((n,(h,w)),(((x,(l,u)),o),((y,f),(v,r)))),((t,(((c,a),(g,(z,d))),i)),(e,s)))
```

I think it's almost the same as the picture above, just 'v' and 'y' are replaced.

I used the message string:

```python
'thissentencecontainsthreeasthreecstwodstwentysixesfivefsthreegseighthsthirteenistwolssixteennsnineossixrstwentysevensstwentytwotstwousfivevseightwsfourxsfiveysandonlyonez'
```

**Comment by jeffgerickson** [comment]
@erbenpeter You have exactly the same code lengths as me, so I must be calculating the encoded message length incorrectly.  Working...

**Comment by jeffgerickson** [comment]
Yup, I can't do arithmetic.  So there were **two** errors here, one in constructing the code and the other in computing its cost.  Both fixed now (locally).
