### ISSUE TITLE
ch2.6 p84 Last digit of Pi is incorrect

### ISSUE THREAD

**Issue by MarkJeronimus** [jeffgerickson/algorithms#89]
The last digit of pi should be 6 not 7, because **unrounded** it continues 6(43383...)

**Comment by jeffgerickson** [comment]
<snark> Who said that was π? </snark>

**Comment by MarkJeronimus** [comment]
The first 22 digits 🤷

**Comment by jeffgerickson** [comment]
Yep.  Good catch!
