### ISSUE TITLE
Quick sort partition problem

### ISSUE THREAD

**Issue by kigawas** [jeffgerickson/algorithms#90]
**Please verify that the error is present in the most recent revision before reporting.**

**Chapter number or note title:** [title]
Recursion

**Page number:** [page]
Recursion 9

**Error description:** [error]
It should swap A[n] with A[l+1] in quick sort partition
![image](https://user-images.githubusercontent.com/4182346/51822545-074e2c00-2320-11e9-8131-75643c3cfce5.png)

**Suggested fix (if any):** [fix]

**Comment by XBOOS** [comment]
Agree. Also found this in the latest pdf version.

**Comment by XBOOS** [comment]
Hi I found this already solved in https://github.com/jeffgerickson/algorithms/issues/32
