### ISSUE TITLE
Inconsistent set names in 11.3

### ISSUE THREAD

**Issue by ruds** [jeffgerickson/algorithms#91]
**Please verify that the error is present in the most recent revision before reporting.** ✓

**Chapter number or note title:** 11.3 Bipartite Matching

**Page number:** 354-355

**Error description:** The description of the maximum flow reduction alternates between the use of L and R for two sets of nodes, and U and W for the same sets. We are also left to infer that L (or U) refers to the doctor nodes and R (or W) refers to the hospital nodes.

**Comment by jeffgerickson** [comment]
> The description of the maximum flow reduction alternates between the use of L and R for two sets of nodes, and U and W for the same sets.

Fixed.

> We are also left to infer that L (or U) refers to the doctor nodes and R (or W) refers to the hospital nodes.

Good.  No change.
