### ISSUE TITLE
[Typo] Chapter 3 page 25 (119 in book) superfluous 'to'

### ISSUE THREAD

**Issue by zx9w** [jeffgerickson/algorithms#98]
[This version](http://jeffe.cs.illinois.edu/teaching/algorithms/book/Algorithms-JeffE.pdf) has the problem, I'd assume that it's the most recent one?

Chapter 3, below the picture of the trees, page 119.

There was probably a more imperative description of the problem originally and the "to" got left behind when editing.

> (In principle, we could use an array instead, but then we’d have **to** pointers back and forth between each node and its corresponding array entry, so why bother?)

(emphasis added)

**Comment by jeffgerickson** [comment]
replaced "have to" with "need"
